---
title: "ML-CFA Trace Plots: Factor Loadings"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r init, warning=FALSE, message=FALSE}
rm(list=ls())
source(paste0(getwd(),"/code/load_packages.R"))
source(paste0(getwd(),"/code/get_data.R"))

sim_results <- filter(sim_results, Converge==1 & Admissible==1)

# compute average loading

sim_results <- sim_results %>%
  group_by(Condition, Replication, Estimator) %>%
  mutate(
    lambda = mean(c(lambda11, lambda12, lambda13,
                    lambda14, lambda15, lambda16,
                    lambda26, lambda27, lambda28,
                    lambda29, lambda210))
  )

```


# Trace Plots of Average Loading

## Over All Conditions

```{r all-c}

plot_dat <- sim_results

p <- ggplot(plot_dat, aes(x=Replication, y=lambda, 
                         group=interaction(Estimator, Condition),
                         color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading')+
  theme_bw() +
  theme(panel.grid = element_blank())
p
#ggsave("fig/loading-converge.pdf", plot=p, width=7, height=4, units="in")

p <- ggplot(plot_dat, aes(x=Replication, y=lambda, 
                         group=Estimator,
                         color=Estimator)) +
  geom_line(alpha=0.75) +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  facet_wrap(.~Condition, scales="free")+
  labs(y='Factor Loading')+
  theme_bw() +
  theme(panel.grid = element_blank())
p

```



```{r}
plot_dat <- filter(sim_results, ss_l2==100, ss_l1==10,
                  icc_lv==0.1, icc_ov==0.3)
p <- ggplot(plot_dat, aes(x=Replication, y=lambda, 
                         group=Estimator, color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading (Item 1)')+
  theme_bw()
p
ggsave("fig/loading-converge-medN.pdf", plot=p, width=7, height=4, units="in")

## Large N
plot_dat <- filter(sim_results, ss_l2==200, ss_l1==10,
                  icc_lv==0.1, icc_ov==0.3)
p <- ggplot(plot_dat, aes(x=Replication, y=lambda11, 
                         group=Estimator, color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading (Item 1)')+
  theme_bw()
p
ggsave("fig/loading-converge-largeN.pdf", plot=p, width=7, height=4, units="in")

```



```{r}

# Small N
plot_dat <- filter(sim_results, ss_l2==30, ss_l1==10,
                  icc_lv==0.1, icc_ov==0.3)
p <- ggplot(plot_dat, aes(x=Replication, y=lambda11, 
                         group=Estimator, color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading (Item 1)')+
  theme_bw()
p
ggsave("fig/loading-converge-smallN.pdf", plot=p, width=7, height=4, units="in")
# Medium N
plot_dat <- filter(sim_results, ss_l2==100, ss_l1==10,
                  icc_lv==0.1, icc_ov==0.3)
p <- ggplot(plot_dat, aes(x=Replication, y=lambda11, 
                         group=Estimator, color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading (Item 1)')+
  theme_bw()
p
ggsave("fig/loading-converge-medN.pdf", plot=p, width=7, height=4, units="in")

## Large N
plot_dat <- filter(sim_results, ss_l2==200, ss_l1==10,
                  icc_lv==0.1, icc_ov==0.3)
p <- ggplot(plot_dat, aes(x=Replication, y=lambda11, 
                         group=Estimator, color=Estimator)) +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype="dashed")+
  labs(y='Factor Loading (Item 1)')+
  theme_bw()
p
ggsave("fig/loading-converge-largeN.pdf", plot=p, width=7, height=4, units="in")

```



```{r session-info}
sessionInfo()
```

